version: "3"
services:
  gitlab:
    restart: always
    image: genshen/gitlab:latest
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:8181"
    - "2222:22"
    volumes:
    - ./config:/etc/gitlab
    - ./data/gitlab:/gitlab/data
    - ./data/gitlab/gitlab-logs:/var/log/gitlab

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    command:
    - --loglevel warning
    volumes:
    - ./data/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-pg-with-pg_trgm
    image: postgresql-with-pg_trgm
    container_name: postgresql
    volumes:
    - ./data/postgresql:/var/lib/postgresql/data:Z
    environment:
    - POSTGRES_USER=git
    - POSTGRES_PASSWORD=secure_password
    - POSTGRES_DB="gitlabhq_production"
    - PGDATA=/var/lib/postgresql/data